import LocalizedStrings from 'react-localization';

const localisations = new LocalizedStrings({
    pl: {
        pageTitle: 'Stacja pomiaru zanieczyszczenia powietrza przez pyły zawieszone PM1, PM2.5, PM10',
        schoolName: 'Zespół Szkół Politechnicznych im. Bohaterów Monte Cassino we Wrześni',

        data: 'Dane',
        particulateMatterInformation: 'Pyły zawieszone',
        norms: 'Normy',
        howDoesItWork: 'Jak to działa?',
        aboutTheProject: 'O projekcie',

        homePageTitle: 'O projekcie',
        welcomeTitle: 'Witamy na stronie stacji pomiaru zanieczyszczenia powietrza pyłami zawieszonymi PM1, PM2.5 oraz PM10.',
        createdInformation: 'Stacja została stworzona przez uczniów Zespołu Szkół Politechnicznych im. Bohaterów Monte Cassino we Wrześni w ramach projektu Code for Green:',
        softwareAndWebsite: 'oprogramowanie czujnika, strona internetowa',
        informationSections: 'przygotowanie sekcji informacyjnych',
        case: 'obudowa czujnika',

        records: 'Rekordy',
        chart: 'Wykres',
        chooseAnOptionToContinue: 'Wybierz jedną z powyższych opcji, aby\xa0kontynuować',
        emptyRequestResult: 'Brak danych w tym przedziale czasowym',
        start: 'Początek',
        end: 'Koniec',
        day: 'Dzień',
        week: 'Tydzień',
        month: 'Miesiąc',
        datetime: 'Data i godzina pomiaru',

        particulateMatterInformationTitle: 'Pyły zawieszone',
        particulateMatterIntro: 'W powietrzu, choć\xa0o tym sami nie wiemy znajdują się pyły zawieszone, które\xa0są szkodliwe dla naszego zdrowia.',
        particulateMatterSize: ' Wielkość ich cząsteczek podaje się w mikrometrach (µm) - 0,000001 × 1 m, największe z nich mają do 0,00001 m co sprawia, że\xa0są dla nas niezauważalne.',
        particulateMatterDivision: 'Dzielą się one na:',
        pm10: 'PM10 - to największe ze śledzonych w smogu cząsteczek pyły zawieszone. Rozmiar: od 2.5μm do 10μm. PM10 zatrzymują się w nosie, zatokach, gardle. Mogą powodować astmę czy\xa0też katar. Większość tego rodzaju pyłów powstaje wskutek ogrzewania prywatnych domów, a\xa0także ruchu drogowego. Podrażniają również nasze oczy przyczyniając się do wystąpienia zapalenia spojówek. W ciągu roku przekroczenie 24 godzinnego stężenia nie może zdarzyć się częściej niż 35 razy.',
        pm25: 'PM2.5 – rozmiar od 1 do 2,5μm. Takie cząsteczki bez przeszkód przedostają się do układu oddechowego, a\xa0następnie do krwi. Długotrwały kontakt z pyłami PM2.5 może doprowadzić do nadciśnienia, a\xa0także poważniejszych chorób układu krążenia (w tym również zawałów serca). Drobne cząsteczki mają negatywny wpływ na zdrowie kobiet w ciąży, a\xa0także płodu (mogą przyczynić się nawet do wystąpienia wad wrodzonych).',
        pm1: 'PM1 – rozmiar mniejszy od 1μm. Zdecydowanie najbardziej niebezpieczne z pyłów zawieszonych ze względu na rozmiar ich cząsteczki, które\xa0przenikają z płuc do krwi, a\xa0następnie do innych narządów. Są również niebezpieczne dla przyszłych mam i\xa0ich dzieci. Długotrwałe oddychanie powietrzem, w którym\xa0stężenie pyłów PM1 jest przekroczone może doprowadzić nawet do powstania nowotworów. Nie ma odgórnej określonej normy ustalonej przez UE.',

        normsTitle: 'Normy',
        normsIntro: 'Istnieją określone normy i\xa0średnie wartości dla zawartości pyłów zawieszonych w powietrzu. W Polsce regulowane są one przez Główny Inspektorat Średowiska oraz\xa0Unię Europejską.',
        normsForOtherSubstances: 'Przepisy unijne określają również poziomy informowania i\xa0alarmowania dla stężenia innych substancji przypadającego na jedną godzinę, na przykład dla ozonu O³ - odpowiednio 180 i\xa0240 µg/m³.',
        comparisonTitle: 'Porównanie norm zanieczyszczeń w krajach Unii Europejskiej',
        country: 'Kraj lub Unia Europejska',
        pl: 'Polska',
        eu: 'Unia Europejska',
        be: 'Belgia',
        cz: 'Czechy',
        fi: 'Finlandia',
        fr: 'Francja',
        sk: 'Słowacja',
        ch: 'Szwajcaria',
        hu: 'Węgry',
        it: 'Włochy',
        gb: 'Wielka Brytania',
        allowedDailyLevel: 'dobowy poziom dopuszczalny',
        informingDailyLevel: 'dobowy poziom informowania',
        alertDailyLevel: 'dobowy poziom alarmowania',
        highLevel: 'wysoki poziom',
        averageYearlyAllowedLevel: 'średni roczny poziom dopuszczalny',
        sources: 'Źródła',

        howDoesItWorkTitle: 'Jak to działa?',
        howDoesItWorkDescription: 'W naszym projekcie chcąc sprawdzić jakość powietrza w naszej okolicy użyliśmy czujnika pyłu zawieszonego Plantower PMS5003. Dane z niego przez interfejs UART trafiają do prostego, działającego w oparciu o system Linux minikomputera Raspberry Pi 3 B+, który\xa0dodaje je do bazy danych. Sam czujnik działa w oparciu o obserwację rozproszenia światła laserowego na cząstkach pyłu zawieszonego w powietrzu, dzięki\xa0czemu\xa0wykrywa:',
        howDoesItWorkA: 'około 50% cząstek o średnicy 0.3μm',
        howDoesItWorkB: 'około 98% cząsteczek o średnicy 0.5μm',
        howDoesItWorkAfter: 'Umożliwia nam to zebranie w miarę dokładnych danych do prezentacji i\xa0analizy.'
    },
    en: {
        pageTitle: 'Measurement station for air pollution by the PM1, PM2.5, PM10 particulate matter',
        schoolName: 'Zespół Szkół Politechnicznych im. Bohaterów Monte Cassino (Heroes of Monte Cassino Polytechnic School Complex) in Września',

        data: 'Data',
        particulateMatterInformation: 'Particulate matter',
        norms: 'Norms',
        howDoesItWork: 'How does it work?',
        aboutTheProject: 'About the project',

        homePageTitle: 'About the project',
        welcomeTitle: 'Welcome to the website of the air pollution measurement station for the PM1, PM2.5 and\xa0PM10 particulate matter.',
        createdInformation: 'The station was created by students of the Zespół Szkół Politechnicznych im. Bohaterów Monte Cassino (Heroes of Monte Cassino Polytechnic School Complex) in Września as part of the Code for Green project:',
        softwareAndWebsite: "sensor's software, website",
        informationSections: 'preparation of the information sections',
        case: "sensor's case",

        records: 'Records',
        chart: 'Chart',
        chooseAnOptionToContinue: 'Select one of the options above to continue',
        emptyRequestResult: 'No data in this timespan',
        start: 'Start',
        end: 'End',
        day: 'Day',
        week: 'Week',
        month: 'Month',
        datetime: 'Date and\xa0hour of the measurement',

        particulateMatterInformationTitle: 'Particulate matter',
        particulateMatterIntro: "Although we don't know about it ourselves, there is particulate matter in the air, which is harmful to our health.",
        particulateMatterSize: 'The size of their particles is given in micrometers (µm) - 0.000001 × 1 m, the largest ones are up to 0.00001 m, making them unnoticeable to us.',
        particulateMatterDivision: 'They are divided into:',
        pm10: 'PM10 - is the largest traced in smog  particulate matter. Size: from 2.5μm to 10μm. PM10 stops in the nose, sinuses, throat. They can cause asthma or rhinitis. Most of these dusts are generated by heating private homes as well as traffic. They also irritate our eyes and\xa0contribute to conjunctivitis. A 24-hour concentration must not be exceeded more than 35 times per year.',
        pm25: 'PM2.5 - size from 1 to 2.5μm. Such molecules easily get into the respiratory system and\xa0then into the blood. Long-lasting contact with PM2.5 dusts may lead to hypertension as well as more serious cardiovascular diseases (including heart attacks). Small particles have a negative impact on the health of pregnant women as well as the fetus (they can even contribute to birth defects).',
        pm1: 'PM1 - size less than 1μm. Definitely the most dangerous of suspended dusts due to their particle size, which get from lungs to blood and\xa0then to other organs. They are also dangerous for future mothers and\xa0their children. Breathing with the air in which the concentration of PM1 dust is exceeded for a long time can even lead to cancer. There is no top-down standard set by the EU.',

        normsTitle: 'Norms',
        normsIntro: 'There are specific standards and\xa0average values for airborne dust content. In Poland they are regulated by the Chief Inspectorate of the Environment and\xa0the European Union.',
        normsForOtherSubstances: 'Union legislation also specifies information and\xa0alert levels for concentrations of other substances per hour, for example 180 and\xa0240 µg/m³ for the ozone O³ respectively.',
        comparisonTitle: 'Comparison of the pollution standards in European Union countries',
        country: 'Country or the European Union',
        pl: 'Poland',
        eu: 'European Union',
        be: 'Balgium',
        cz: 'Czech Republik',
        fi: 'Finland',
        fr: 'France',
        sk: 'Slovakia',
        ch: 'Switzerland',
        hu: 'Hungary',
        it: 'Italy',
        gb: 'Great Britain',
        allowedDailyLevel: 'daily allowed level',
        informingDailyLevel: 'daily information level',
        alertDailyLevel: 'daily alert level',
        highLevel: 'high level',
        averageYearlyAllowedLevel: 'average yearly allowed level',
        sources: 'Sources',

        howDoesItWorkTitle: 'How does it work?',
        howDoesItWorkDescription: 'In our project, to check the air quality in our area, we used the Plantower PMS5003 particulate matter sensor. The data from it goes through the UART interface to a simple Linux-based Raspberry Pi 3 B+ minicomputer, which adds it to the database. The sensor itself works by observing the scattering of laser light on airborne dust particles and\xa0thus detects:',
        howDoesItWorkA: 'about 50% of particles with the diameter of 0.3μm',
        howDoesItWorkB: 'about 98% of particles with the diameter 0.5μm',
        howDoesItWorkAfter: 'This enables us to collect fairly accurate data for the purposes of presentation and\xa0analysis.'
    }
});

export default localisations;